= README

Implements the cosine similarity algorithm as described in
https://www.geeksforgeeks.org/cosine-similarity/. (Note: We have an
another less-standard algorithm in our examplar assignment
https://cs.brown.edu/courses/csci0190/2023/docdiff.html.)

We'd like to store the input documents in Google Drive. Currently
the only Drive documents that we can work with are spreadsheets,
so we add a way to extract the relevant text from a spreadsheet.
We will assume that that the spreadsheets used for this purpose
contain only one cell, which contains the entire text of the
document. We may need to revisit based on any size limitations
imposed by Google Spreadsheets. The first step then would be to
then to spread the text across a single column.

The functions provided:

- `cosine-similarity-lists()` which takes two lists of words
  (strings) and finds the cosine similarity between them.

- `cosine-similarity-files()` which takes two Google Drive IDs,
  and finds the cosine similarity between their respective
  spreadsheet single-cell contents.

- `cosine-similarity()` which takes two strings, and finds teh
  cosine similarity of the list of words contained in the
  respective strings.

Internally, a list of words associated with one document is
uniquified, and a (non-mutable) string-dict is created associating each word
with its count. Thus the list associated with a document maps
(only) the words in it to their counts. We don't need to keep
track of any other words that may appear in comparable documents
(unlike docdiff).

The `dot-product()` of two such string-dicts goes over every key
in the first dict, and if it is also represented in the second
dict, multiplies them. The sum of such multiples is the dot
product.

To normalize this dot-product (i.e., to hem it between 0 and 1),
we divide by the product of the magnitudes of the two
string-dicts. (The magnitude of a string-dict is the square-root of
its dot-product with itself.)

== Other types of similarity

Two other simpler forms of similarity are also provided (with the
same signature as for cosine similarity above):

- `simple-similarity-lists()`, `simple-similarity-files()`, and
  `simple-similarity()`
  check if the words are the same in the same order. Output is
  boolean.

- `bow-similarity-lists()`, `bow-similarity-files()`, and
  `bow-similarity()` check if
  the Bag Of Words are the same (i.e., order doesn't matter, but
  count does). Output is boolean.

== Debugging aid

The function `string-to-bag()` takes a text (string) and after
collapsing case and removing punctuation, returns a table of
rows, where each row lists a word along with its frequency.
